# Generated by Django 4.1.7 on 2023-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantitytype',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('wholesale', 'Оптом'), ('retail', 'В розницу')], default=('retail', 'В розницу'), max_length=50),
        ),
    ]
