# Generated by Django 4.1.7 on 2023-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
