# Generated by Django 4.1.7 on 2023-03-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('product', '0002_product_quantitytype_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='deals.dealcategory'),
        ),
    ]
