# Generated by Django 4.1.7 on 2023-03-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcategory',
            name='Deals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deals_category', to='deals.deals'),
        ),
    ]
