# Generated by Django 4.1.7 on 2023-03-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_dealcategory_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealcategory',
            old_name='Deals',
            new_name='deals',
        ),
    ]
